export const OS_STATUSES=['ABERTA','EM_EXECUCAO','AGUARDANDO_PECA','AGUARDANDO_TERCEIRIZADA','AGUARDANDO_APROVACAO_DIRETOR','CONCLUIDA','CANCELADA'];
export const OPEN_STATUSES=OS_STATUSES.filter(s=>!['CONCLUIDA','CANCELADA'].includes(s));
export const isOpenStatus=s=>OPEN_STATUSES.includes(s);
