const MAX_FILES=8,MAX_SIZE=10*1024*1024;
export class FilePicker{
 constructor(root,{onChange,onError}={}){this.root=root;this.files=[];this.urls=[];this.onChange=onChange;this.onError=onError;this.render();}
 render(){this.root.innerHTML=`<label class="label">Fotos obrigatórias</label><div class="photo-actions"><label class="btn primary photo-btn">📷 Tirar foto<input data-role="camera" type="file" accept="image/*" capture="environment"></label><label class="btn light photo-btn">🖼 Escolher da galeria<input data-role="gallery" type="file" accept="image/*" multiple></label></div><div class="photo-help">Selecione até 8 imagens, com no máximo 10 MB cada. Os campos do formulário não serão apagados.</div><div data-role="count" class="muted mt">Nenhuma foto selecionada</div><div data-role="preview" class="preview"></div>`;this.root.querySelectorAll('input[type=file]').forEach(i=>i.onchange=e=>{this.add(e.target.files);e.target.value=''});this.update();}
 add(list){const incoming=Array.from(list||[]);const accepted=[];for(const f of incoming){if(!f.type?.startsWith('image/')){this.onError?.('Arquivo ignorado: use apenas imagens.');continue}if(f.size>MAX_SIZE){this.onError?.(`Imagem ${f.name} excede 10 MB.`);continue}accepted.push(f)}if(this.files.length+accepted.length>MAX_FILES){this.onError?.(`Limite de ${MAX_FILES} fotos atingido.`);accepted.splice(MAX_FILES-this.files.length)}this.files.push(...accepted);this.update();this.onChange?.(this.files)}
 remove(i){URL.revokeObjectURL(this.urls[i]);this.urls.splice(i,1);this.files.splice(i,1);this.update();this.onChange?.(this.files)}
 update(){this.urls.forEach(URL.revokeObjectURL);this.urls=this.files.map(f=>URL.createObjectURL(f));const count=this.root.querySelector('[data-role=count]');if(count)count.textContent=this.files.length?`${this.files.length} foto(s) selecionada(s)`:'Nenhuma foto selecionada';const p=this.root.querySelector('[data-role=preview]');if(!p)return;p.textContent='';this.files.forEach((f,i)=>{const w=document.createElement('div');w.className='preview-item';const img=document.createElement('img');img.src=this.urls[i];img.alt=f.name;const b=document.createElement('button');b.type='button';b.className='preview-remove';b.textContent='×';b.onclick=()=>this.remove(i);w.append(img,b);p.append(w);});}
 clear(){this.urls.forEach(URL.revokeObjectURL);this.urls=[];this.files=[];this.update();this.onChange?.(this.files)}
 destroy(){this.urls.forEach(URL.revokeObjectURL);this.urls=[];}
}
