import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const checks=[]; const ok=(name,pass,detail='')=>checks.push({name,pass,detail});
const files=['index.html','src/styles.css','src/app.js','src/config/supabase.js','src/state/store.js','src/router.js','src/services/authService.js','src/services/unitService.js','src/services/orderService.js','src/services/equipmentService.js','src/services/preventiveService.js','src/services/catalogService.js','src/services/uploadService.js','src/domain/permissions.js','src/domain/statuses.js','src/domain/priorities.js','src/ui/modal.js','src/ui/toast.js','src/ui/filePicker.js','src/pages/loginPage.js','src/pages/dashboardPage.js','src/pages/technicianPage.js','src/pages/ordersPage.js','src/pages/openOrderPage.js','src/pages/equipmentPage.js','src/pages/preventivePage.js','src/pages/catalogsPage.js','src/pages/auditPage.js','src/pages/costsPage.js','src/pages/usersPage.js','src/pages/reportsPage.js','src/pages/configPage.js'];
for(const f of files) ok(`arquivo existe: ${f}`,fs.existsSync(path.join(root,f)));
const index=read('index.html'),app=read('src/app.js'),picker=read('src/ui/filePicker.js'),statuses=read('src/domain/statuses.js'),perms=read('src/domain/permissions.js'),storeFile=read('src/state/store.js'),unit=read('src/services/unitService.js'),order=read('src/services/orderService.js');
ok('GitHub Pages carrega módulo app',index.includes('type="module"')&&index.includes('./src/app.js'));
ok('Login usa Supabase Auth',app.includes('signIn(')&&app.includes('getSession()'));
ok('Carregamento de perfil via serviço',app.includes('loadProfile(session.user.id)'));
ok('Seleção de unidade existe',app.includes('id="unitSelector"')&&app.includes('loadBase(e.target.value)'));
ok('Troca de unidade recria realtime',app.includes('sb.removeChannel')&&app.includes('startRealtime()'));
ok('Técnico/operador sem troca de unidade privilegiada',storeFile.includes('MASTER')&&storeFile.includes('ADMIN')&&storeFile.includes('DIRETOR')&&app.includes('canSwitchUnits()?store.availableUnits'));
ok('Abertura sem foto bloqueia',app.includes("Adicione pelo menos uma foto"));
ok('Abertura com foto cria OS e envia anexos',app.includes('createOrder(')&&app.includes('uploadFiles(picker.files')&&app.includes('insertAttachment'));
ok('Múltiplas fotos habilitadas',picker.includes('multiple')&&picker.includes('MAX_FILES=8'));
ok('Campos não são recriados ao selecionar foto',picker.includes('this.update()')&&app.includes('form.addEventListener'));
ok('Remover foto funciona',picker.includes('remove(i)')&&picker.includes('splice(i,1)'));
ok('Erro de upload preserva formulário',app.includes('Tentar novamente')&&app.includes('msg.textContent=err.message'));
ok('Duplo clique bloqueado',app.includes('store.isSubmitting')&&app.includes('if(store.isSubmitting)return'));
ok('Técnico não vê cadastros',app.includes('if(isTechnician())return')&&app.includes('if(canManageCatalog())items.splice'));
ok('Administrador vê cadastros',perms.includes('canManageCatalog')&&app.includes('Cadastros'));
ok('OS cancelada não conta aberta',statuses.includes("'CANCELADA'")&&statuses.includes('OPEN_STATUSES')&&app.includes('isOpenStatus(o.status)'));
ok('Custo do mês filtra período',app.includes('monthCosts')&&app.includes('d>=ms&&d<me'));
ok('Todos status nos filtros',statuses.includes('AGUARDANDO_TERCEIRIZADA')&&statuses.includes('AGUARDANDO_APROVACAO_DIRETOR')&&app.includes('OS_STATUSES.map'));
ok('Limite 10 MB por imagem',picker.includes('10*1024*1024'));
ok('Object URLs revogados',picker.includes('URL.revokeObjectURL'));
ok('Sem service_role no frontend',![index,app,read('src/config/supabase.js')].join('\n').includes('service_role'));
let failed=checks.filter(c=>!c.pass); for(const c of checks) console.log(`${c.pass?'PASS':'FAIL'} ${c.name}${c.detail?' - '+c.detail:''}`); if(failed.length){console.error(`\n${failed.length} smoke checks failed.`);process.exit(1)} console.log(`\n${checks.length} smoke checks passed.`);
