import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const checks=[]; const ok=(name,pass)=>checks.push({name,pass});
const files=['index.html','src/styles.css','src/app.js','src/config/supabase.js','src/state/store.js','src/router.js','src/services/authService.js','src/services/unitService.js','src/services/orderService.js','src/services/equipmentService.js','src/services/preventiveService.js','src/services/catalogService.js','src/services/uploadService.js','src/domain/permissions.js','src/domain/statuses.js','src/domain/priorities.js','src/ui/modal.js','src/ui/toast.js','src/ui/filePicker.js','src/pages/loginPage.js','src/pages/dashboardPage.js','src/pages/technicianPage.js','src/pages/ordersPage.js','src/pages/openOrderPage.js','src/pages/equipmentPage.js','src/pages/preventivePage.js','src/pages/catalogsPage.js','src/pages/auditPage.js','src/pages/costsPage.js','src/pages/usersPage.js','src/pages/reportsPage.js','src/pages/configPage.js'];
for(const f of files) ok(`arquivo existe: ${f}`,fs.existsSync(path.join(root,f)));
const index=read('index.html'),app=read('src/app.js'),config=read('src/config/supabase.js');
ok('GitHub Pages carrega app modular',index.includes('type="module"')&&index.includes('./src/app.js')&&index.includes('./src/styles.css'));
ok('Login usa Supabase Auth',app.includes('sb.auth.getSession')&&app.includes('signInWithPassword'));
ok('Perfil é carregado antes da base',app.includes('await loadProfile();')&&app.includes('await loadBase();'));
ok('Seleção de unidade existe para perfis privilegiados',app.includes('id="unitSelector"')&&app.includes('canSwitchUnits()'));
ok('Troca de unidade recarrega base e recria realtime',app.includes('await loadBase(e.target.value);startSync();renderApp()'));
ok('Realtime cancela subscription antiga',app.includes('sb.removeChannel(realtimeChannel)'));
ok('Não há polling setInterval',!app.includes('setInterval('));
ok('Não usa localStorage para dado oficial',!app.includes('localStorage'));
ok('Técnico não recebe item Cadastros',app.includes('if(isTechnician())')&&app.includes('if(canManageCatalog()) items.splice'));
ok('Abertura de OS tem unidade/área/setor/categoria/equipamento/prioridade/problema/descrição',app.includes('name="area_id"')&&app.includes('name="setor_id"')&&app.includes('name="categoria"')&&app.includes('name="equipamento_id"')&&app.includes('name="prioridade"')&&app.includes('name="problema"')&&app.includes('name="descricao"'));
ok('Abertura sem foto bloqueia com mensagem visual',app.includes('openFormMsg')&&app.includes('Adicione pelo menos uma foto do problema'));
ok('Abertura com foto cria OS, faz upload e grava anexos',app.includes('ordens_servico')&&app.includes('uploadFiles(openFiles')&&app.includes('os_anexos'));
ok('Preserva campos após foto',app.includes('saveOpenFormDraft')&&app.includes('restoreOpenFormDraft')&&app.includes('onBeforePick?.()'));
ok('Limita várias fotos a 8 e 10 MB',app.includes('PHOTO_LIMIT=8')&&app.includes('PHOTO_MAX_BYTES=10*1024*1024'));
ok('Câmera e galeria separadas',app.includes('capture="environment"')&&app.includes('Gallery')&&app.includes('multiple'));
ok('Miniaturas e remoção de fotos',app.includes('preview-item')&&app.includes('preview-remove')&&app.includes('target.splice(i,1)'));
ok('Revoga Object URLs',app.includes('URL.revokeObjectURL'));
ok('Duplo envio bloqueado',app.includes('isSubmittingOpenOS')&&app.includes('if(isSubmittingOpenOS)return'));
ok('Erro de upload preserva formulário e fotos',app.includes('Tentar novamente')&&app.includes('restoreOpenFormDraft'));
ok('Todos status estão no filtro',app.includes('OS_STATUSES.map')&&app.includes('AGUARDANDO_TERCEIRIZADA')&&app.includes('AGUARDANDO_APROVACAO_DIRETOR')&&app.includes('CANCELADA'));
ok('Cancelada não conta como aberta',app.includes('OPEN_OS_STATUSES')&&app.includes('isOpenOS'));
ok('Custo do mês filtra pelo período atual',app.includes('d>=monthStart')&&app.includes('getMonth()+1'));
ok('Detalhes e equipamento inexistentes são tratados',app.includes('OS não encontrada ou removida')&&app.includes('Equipamento não encontrado ou removido'));
ok('Anexos e checklist checam erros',app.includes('attachError')&&app.includes('respError')&&app.includes('ncError'));
ok('Sem service_role no frontend',![index,app,config].join('\n').includes('service_role'));
const failed=checks.filter(c=>!c.pass);
for(const c of checks) console.log(`${c.pass?'PASS':'FAIL'} ${c.name}`);
if(failed.length){console.error(`\n${failed.length} smoke checks failed.`);process.exit(1)}
console.log(`\n${checks.length} smoke checks passed.`);
